import {
  Award,
  BadgeCheck,
  Banknote,
  BookOpen,
  BookUser,
  Bookmark,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  ChartBar,
  CircleCheck,
  ClipboardCheck,
  Clock,
  Coins,
  Compass,
  CreditCard,
  FileCheck,
  FileText,
  Flag,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  Handshake,
  Headphones,
  Heart,
  Home,
  Key,
  Languages,
  Laptop,
  Layers,
  Library,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  Lock,
  Luggage,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  NotebookPen,
  PenTool,
  Percent,
  Phone,
  PiggyBank,
  Plane,
  Presentation,
  Rocket,
  Scale,
  School,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  Target,
  ThumbsUp,
  Ticket,
  Timer,
  TrendingUp,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
  HelpCircle,
} from 'lucide-react';

// Canonical icon set. These names are validated by the API and offered by the
// admin picker — keep all three in sync or an icon renders blank on the site.
export const ICONS = {
  'cap': GraduationCap,
  'school': School,
  'library': Library,
  'book-open': BookOpen,
  'notebook-pen': NotebookPen,
  'clipboard-check': ClipboardCheck,
  'file-check': FileCheck,
  'document': FileText,
  'pen-tool': PenTool,
  'presentation': Presentation,
  'award': Award,
  'languages': Languages,
  'plane': Plane,
  'globe': Globe,
  'passport': BookUser,
  'luggage': Luggage,
  'map': Map,
  'pin': MapPin,
  'compass': Compass,
  'ticket': Ticket,
  'flag': Flag,
  'coins': Coins,
  'banknote': Banknote,
  'piggy-bank': PiggyBank,
  'wallet': Wallet,
  'credit-card': CreditCard,
  'hand-coins': HandCoins,
  'percent': Percent,
  'calculator': Calculator,
  'users': Users,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'handshake': Handshake,
  'headphones': Headphones,
  'message-circle': MessageCircle,
  'phone': Phone,
  'mail': Mail,
  'heart': Heart,
  'life-buoy': LifeBuoy,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'badge-check': BadgeCheck,
  'circle-check': CircleCheck,
  'star': Star,
  'thumbs-up': ThumbsUp,
  'lock': Lock,
  'key': Key,
  'target': Target,
  'search': Search,
  'briefcase': Briefcase,
  'building-2': Building2,
  'clock': Clock,
  'timer': Timer,
  'calendar': Calendar,
  'calendar-check': CalendarCheck,
  'home': Home,
  'trending-up': TrendingUp,
  'chart-bar': ChartBar,
  'list-checks': ListChecks,
  'layers': Layers,
  'lightbulb': Lightbulb,
  'rocket': Rocket,
  'sparkles': Sparkles,
  'settings': Settings,
  'send': Send,
  'bookmark': Bookmark,
  'gift': Gift,
  'scale': Scale,
  'stethoscope': Stethoscope,
  'laptop': Laptop,
};

export const ICON_NAMES = Object.keys(ICONS);

export default function Icon({ name, size = 24, strokeWidth = 1.8, className }) {
  const Cmp = ICONS[name] || HelpCircle;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />;
}
